# Generated by Django 3.2.3 on 2021-05-27 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_transport_charges_transaction_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='warh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.warehouse'),
        ),
    ]
