# Generated by Django 3.2.3 on 2021-05-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transaction_warh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cod',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchase_title',
            field=models.CharField(max_length=1000),
        ),
    ]
