# Generated by Django 3.2.3 on 2021-05-27 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210527_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReductionFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transaction')),
            ],
        ),
    ]
