# Generated by Django 3.2.3 on 2021-05-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reductionfine'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='short_name',
            field=models.CharField(default='YP', max_length=2),
        ),
    ]
