# Generated by Django 3.2.3 on 2021-05-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_warehouse_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='download_current_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='download_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='download_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
