# Generated by Django 3.2.3 on 2021-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210530_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='download_end_date',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='download_current_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='download_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
