# Generated by Django 3.2.3 on 2021-05-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210530_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
