# Generated by Django 3.2.3 on 2021-06-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_warehouse_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='datetime',
            new_name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='download_current_date',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='download_start_date',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='download_status',
            field=models.BooleanField(default=False, verbose_name='Статус загрузки архивных данных (запустить/остановить)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='end_date_download',
            field=models.DateField(blank=True, null=True, verbose_name='Конечная дата для скачивания архивных данных'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='last_download_date',
            field=models.DateField(blank=True, null=True, verbose_name='Последняя дата уже скачанных архивных данных'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='start_date_download',
            field=models.DateField(blank=True, null=True, verbose_name='Начальная дата для скачивания архивных данных'),
        ),
    ]
