# Generated by Django 3.2.3 on 2021-06-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210603_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prolongation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('transact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transaction')),
            ],
        ),
    ]
