# Generated by Django 3.2.3 on 2021-11-23 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_warehouse_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prolongation',
            name='transact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transaction', unique=True),
        ),
        migrations.AlterField(
            model_name='reductionfine',
            name='transact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transaction', unique=True),
        ),
    ]
