# Generated by Django 3.2.3 on 2021-12-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211123_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='target',
            field=models.CharField(max_length=220),
        ),
    ]
